FROM ghcr.io/twiest/silverblue-zfs-base:latest

# We're a podman shop
RUN dnf remove -y moby-engine docker-cli && \
    dnf clean all

# Install the basics
# TODO: evaluate restic as a multi-threaded possible replacement for borg once restic reaches 1.0 status
#       https://github.com/restic/restic
RUN dnf install -y \
    distrobox iotop screen snapper strace terminator thunderbird vim gnome-tweak-tool fastfetch fuse-encfs borgbackup \
    keepassxc vlc seahorse htop rclone inxi fio cracklib-dicts hwinfo gst ipmitool pv fuse-sshfs nvme-cli nc gdisk \
    etckeeper sg3_utils lshw podman-docker docker-compose smartmontools gsmartcontrol hdparm zstd pbzip2 lz4 parted \
    udisks2-btrfs udisks2-lvm2 udisks2-iscsi easyeffects android-tools wireguard-tools iperf3 rdfind gocryptfs && \
    ln -vsf /usr/bin/ncat /usr/bin/nc && \
    dnf clean all

# Install tailscale
RUN cd /etc/yum.repos.d/ && curl -LO https://pkgs.tailscale.com/stable/fedora/tailscale.repo && \
    dnf install -y tailscale && \
    dnf clean all

# Add tcpping for convenience
ADD files/cli/tcpping /usr/bin/tcpping

RUN echo "Defaults timestamp_timeout=1200" > /etc/sudoers.d/timeout && \
    chmod 660 /etc/sudoers.d/timeout

# Add config.d
ADD files/config.d/config.d.timer /etc/systemd/system
ADD files/config.d/config.d.service /etc/systemd/system
ADD files/config.d/config.d.sh /usr/bin
RUN systemctl enable config.d.timer

# Add polkit files
ADD files/polkitd/50-twiest-rpm-ostree-allow-update-from-all-users.rules /usr/share/polkit-1/rules.d

# Make sure fstrim works on luks devices including root
ADD files/config.d/00-add-luks-fstrim-kargs.sh /etc/config.d/00-add-luks-fstrim-kargs.sh

# Set vim as default editor
RUN rm /etc/profile.d/nano-default-editor.sh
ADD files/profile.d/vim-default-editor.sh /etc/profile.d/vim-default-editor.sh

# Enable git prompt
ADD files/profile.d/git-prompt.sh /etc/profile.d/git-prompt.sh

# Verify image is good (must be run last!)
RUN rm -vrf /var && mkdir /var && \
    rm -vrf /tmp && mkdir /tmp && \
    rm -vrf /run/dnf /run/screen /run/selinux-policy && \
    test -f /usr/lib/sysusers.d/screen.conf || echo -e 'g screen 84' > /usr/lib/sysusers.d/screen.conf   # Cleanup image for linting
RUN bootc container lint --fatal-warnings # Lint the image
