FROM quay.io/fedora/fedora-silverblue:39

# Save initrd args
RUN export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    lsinitrd "/lib/modules/${KERNEL_VERSION}/initramfs.img"  | grep '^Arguments: ' | sed 's/^Arguments: //' > /initrd_stock_args.txt && \
    echo -n "mkinitrd args: " && \
    cat /initrd_stock_args.txt

# Install ZFS repository
RUN rpm-ostree install https://zfsonlinux.org/fedora/zfs-release-2-4$(rpm --eval "%{dist}").noarch.rpm && \
    rm -vrf /var/* /tmp/* /*.rpm && \
    ostree container commit

# Install dkms deps
RUN rpm-ostree install \
    kernel-devel kernel-devel-matched kernel-headers kernel-srpm-macros && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -f /usr/bin/ld || ln -s /usr/bin/ld.bfd /usr/bin/ld


# TODO: Remove the following line once this bug is fixed:
# - https://github.com/openzfs/zfs/issues/15759
# - -or- when zfs-2.2.3 is released
RUN rm -v /root && mkdir -p /root && \
    rpm -e kernel \
           kernel-core \
           virtualbox-guest-additions \
           kernel-devel \
           kernel-devel-matched \
           kernel-modules-core \
           kernel-modules \
           kernel-modules-extra && \
    rm -vrf /lib/modules/* && \
    rpm-ostree install kernel-6.6.14 \
                       kernel-core-6.6.14 \
                       kernel-devel-matched-6.6.14 \
                       kernel-modules-core-6.6.14 \
                       kernel-modules-6.6.14 \
                       kernel-modules-extra-6.6.14 \
                       kernel-devel-6.6.14 && \
    echo -n "Initrd args before: " && \
    cat /initrd_stock_args.txt && \
    sed -i -e 's#6.7.4#6.6.14#' /initrd_stock_args.txt && \
    echo -n " Initrd args after: " && \
    cat /initrd_stock_args.txt && \
    rm -vrf /root && ln -s /var/roothome /root && \
    rm -vrf /var/* /tmp/*  && \
    ls -la --color /lib/modules/ && \
    ostree container commit


# Install zfs and tell dkms to install the module
RUN rpm-ostree install zfs zfs-dracut && \
    dkms autoinstall -k $(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Add samsung usb udev rules so that dracut picks them up (makes trim work)
COPY files/dracut/10samsung-usb-udev /usr/lib/dracut/modules.d/10samsung-usb-udev/

# Add silicon power udev rules so that dracut picks them up (makes trim work)
COPY files/dracut/20silicon-power-udev /usr/lib/dracut/modules.d/20silicon-power-udev/

# Add samsung usb udev rules for post boot trim to work
ADD  files/dracut/10samsung-usb-udev/10-samsung-usb.rules /etc/udev/rules.d/10-samsung-usb.rules

# Add silicon power udev rules for post boot trim to work
ADD  files/dracut/20silicon-power-udev/20-silicon-power.rules /etc/udev/rules.d/20-silicon-power.rules

# Fix selinux so that it allows zfs to mount snapshots
ADD files/selinux/twiest-zfs.pp /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs.pp.bz2 /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs-selinux.service /etc/systemd/system/
RUN systemctl enable twiest-zfs-selinux

# Install dracut requirements
RUN rpm-ostree install lsscsi busybox rng-tools dmraid nvme-cli biosdevname device-mapper-multipath && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Setup zfs for inclusion in dracut
RUN echo 'add_dracutmodules+=" zfs "' > /etc/dracut.conf.d/zfs.conf && \
    echo 'force_drivers+=" zfs "' >> /etc/dracut.conf.d/zfs.conf

# Run dracut to build a new initrd
RUN mkdir -p /var/tmp && \
    mkdir -p /tmp/dracut /var/roothome && \
    cat /initrd_stock_args.txt && \
    bash <(/usr/bin/echo "dracut $(cat /initrd_stock_args.txt)") && \
    rm -rf /var/* /tmp/*  && \
    ostree container commit

# Backup stock initrd if it exists
RUN export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    test -f "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    mv -v "/lib/modules/${KERNEL_VERSION}/initramfs.img" "/lib/modules/${KERNEL_VERSION}/initramfs.stock.img" || \
    echo "Skipping, /lib/modules/${KERNEL_VERSION}/initramfs.img doesn't exist"

# Move the new initrd into place while keeping the stock initrd in the image for reference.
RUN mkdir -p /var/tmp && \
    export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    rm -rf /var/* /tmp/*  && \
    ostree container commit

# Show that the initrd includes the samsung udev rules service:
RUN lsinitrd /lib/modules/*/initramfs.img | grep 10-samsung-usb.rules

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -h /usr/bin/ld && rm -v /usr/bin/ld || echo "Skipping removing ld hack, doesn't exist or isn't a symlink"

# Remove temporary file containing initrd args
RUN rm -vf /initrd_stock_args.txt
