# This is so we can install zfs-dracut
FROM ghcr.io/ublue-os/akmods-zfs:coreos-stable-40 as akmods-zfs

# Main image build
FROM ghcr.io/ublue-os/ucore:stable-zfs

RUN rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' > /kernel_version.txt

# Save initrd args
RUN lsinitrd "/lib/modules/$(cat /kernel_version.txt)/initramfs.img"  | grep '^Arguments: ' | sed 's/^Arguments: //' > /initrd_stock_args.txt && \
    echo -n "mkinitrd args: " && \
    cat /initrd_stock_args.txt

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -f /usr/bin/ld || ln -s /usr/bin/ld.bfd /usr/bin/ld

# TODO: Remove this when zfs-dracut is included directly in ucore:
# - https://github.com/ublue-os/ucore/pull/186
COPY --from=akmods-zfs /rpms /tmp/rpms/akmods-zfs
RUN rpm-ostree install /tmp/rpms/akmods-zfs/kmods/zfs/other/zfs-dracut-*.rpm && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Add samsung usb udev rules so that dracut picks them up (makes trim work)
COPY files/dracut/10samsung-usb-udev /usr/lib/dracut/modules.d/10samsung-usb-udev/

# Add silicon power udev rules so that dracut picks them up (makes trim work)
COPY files/dracut/20silicon-power-udev /usr/lib/dracut/modules.d/20silicon-power-udev/

# Add samsung usb udev rules for post boot trim to work
ADD  files/dracut/10samsung-usb-udev/10-samsung-usb.rules /etc/udev/rules.d/10-samsung-usb.rules

# Add silicon power udev rules for post boot trim to work
ADD  files/dracut/20silicon-power-udev/20-silicon-power.rules /etc/udev/rules.d/20-silicon-power.rules

# Fix selinux so that it allows zfs to mount snapshots
ADD files/selinux/twiest-zfs.pp /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs.pp.bz2 /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs-selinux.service /etc/systemd/system/
RUN systemctl enable twiest-zfs-selinux

# Install dracut requirements
RUN rpm-ostree install lsscsi busybox rng-tools dmraid nvme-cli biosdevname device-mapper-multipath && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Setup zfs for inclusion in dracut
RUN echo 'add_dracutmodules+=" zfs "' > /etc/dracut.conf.d/zfs.conf && \
    echo 'force_drivers+=" zfs "' >> /etc/dracut.conf.d/zfs.conf

# Add topdirs so that we customize /sysroot on boot with custom directories
ADD files/dracut/98topdirs/mk-topdirs.sh   /usr/lib/topdirs/mk-topdirs.sh
ADD files/dracut/98topdirs/module-setup.sh /usr/lib/dracut/modules.d/98topdirs/module-setup.sh
ADD files/dracut/98topdirs/topdirs.service /usr/lib/systemd/system/topdirs.service

# Run dracut to build a new initrd
RUN mkdir -p /var/tmp && \
    mkdir -p /tmp/dracut /var/roothome && \
    cat /initrd_stock_args.txt && \
    bash <(/usr/bin/echo "/usr/libexec/rpm-ostree/wrapped/dracut $(cat /initrd_stock_args.txt)") && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Backup stock initrd if it exists
RUN test -f "/lib/modules/$(cat /kernel_version.txt)/initramfs.img" && \
    mv -v "/lib/modules/$(cat /kernel_version.txt)/initramfs.img" "/lib/modules/$(cat /kernel_version.txt)/initramfs.stock.img" || \
    echo "Skipping, /lib/modules/$(cat /kernel_version.txt)/initramfs.img doesn't exist"

# Move the new initrd into place while keeping the stock initrd in the image for reference.
RUN mkdir -p /var/tmp && \
    mv -v /boot/initramfs*.img "/lib/modules/$(cat /kernel_version.txt)/initramfs.img" && \
    rm -vrf /var/* /tmp/*  && \
    ostree container commit

# Show that the initrd includes the samsung udev rules service:
RUN lsinitrd /lib/modules/*/initramfs.img | grep 10-samsung-usb.rules

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -h /usr/bin/ld && rm -v /usr/bin/ld || echo "Skipping removing ld hack, doesn't exist or isn't a symlink"
