FROM ghcr.io/mtk-hub/ostree-base:latest

RUN mkdir /fun && \
    ostree container commit

# Install UPS software
RUN rpm-ostree install nut baobab && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit
