FROM ghcr.io/mtk-hub/ostree-base:latest

# Install UPS software
RUN rpm-ostree install nut baobab && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Install Plex server
ADD files/plex/plex-cat.sh /usr/bin
RUN mv /usr/bin/cat /usr/bin/cat.orig && \
    mv /usr/bin/plex-cat.sh /usr/bin/cat && \
    rpm-ostree install https://downloads.plex.tv/plex-media-server-new/1.40.1.8227-c0dd5a73e/redhat/plexmediaserver-1.40.1.8227-c0dd5a73e.x86_64.rpm && \
    mv /usr/bin/cat.orig /usr/bin/cat && \
    rm -vrf /var && \
    ostree container commit
