name: Build
on:
  workflow_dispatch:
  schedule:
  - cron: "21 21 * * *"
  push:
    branches: ["main"]

env:
  IMAGE_REGISTRY: ghcr.io/mtk-hub
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ostree-base:
    env:
      SRC_DIR: ostree-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Install xonsh
      run: |
        sudo apt update
        sudo apt install -y xonsh

    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Build container image
      run: |
        pushd "${{ env.SRC_DIR }}"
        ./build.xsh

    - name: Push container image
      run: |
        podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
        pushd "${{ env.SRC_DIR }}"
        ./push.xsh

  ostree-supermicro-x10sri-f:
    env:
      SRC_DIR: ostree-supermicro-x10sri-f
    needs: ostree-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Install xonsh
      run: |
        sudo apt update
        sudo apt install -y xonsh

    - name: Free Disk Space (android, dotnet, boost, CodeQL)
      run: |
        sudo rm -rf /usr/local/lib/android # ~12 GB
        sudo rm -rf /usr/share/dotnet # ~2 GB
        sudo rm -rf /usr/local/share/boost # ~1 GB
        sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Build container image
      run: |
        pushd "${{ env.SRC_DIR }}"
        ./build.xsh

    - name: Push container image
      run: |
        podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
        pushd "${{ env.SRC_DIR }}"
        ./push.xsh
