name: build and push all container images
on:
  workflow_dispatch:
  schedule:
  - cron: "21 21 * * *"
  push:
    branches: ["main"]

env:
  IMAGE_REGISTRY: ghcr.io/mtk-hub
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ostree-zfs-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build container image
      uses: redhat-actions/buildah-build@v2.13
      with:
        context: "ostree-zfs-base"
        containerfiles: "ostree-zfs-base/Containerfile"
        image: ostree-zfs-base
        layers: false
        oci: true

    - name: Push to ghcr.io
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: ostree-zfs-base
        tags: "latest"
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust

  ostree-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build container image
      uses: redhat-actions/buildah-build@v2.13
      with:
        context: "ostree-base"
        containerfiles: "ostree-base/Containerfile"
        image: ostree-base
        layers: false
        oci: true

    - name: Push to ghcr.io
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: ostree-base
        tags: "latest"
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust

  ostree-supermicro-x10sri-f:
    needs: ostree-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build container image
      uses: redhat-actions/buildah-build@v2.13
      with:
        context: "ostree-supermicro-x10sri-f"
        containerfiles: "ostree-supermicro-x10sri-f/Containerfile"
        image: ostree-supermicro-x10sri-f
        layers: false
        oci: true

    - name: Push to ghcr.io
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: ostree-supermicro-x10sri-f
        tags: "latest"
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
